language: node_js
node_js:
    - '8'
    - '10'
cache:
    yarn: true
    directories:
        - 'node_modules'
install: make install-ci
script: make test-ci
after_success:
    - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false
env:
    - CODECOV_TOKEN=c3faff5c-4c64-4a92-af0f-93047268b1b6

